### ISSUE TITLE
When we run the sample app, we get an exception: "Unable to simultaneously satisfy constraints".

### ISSUE THREAD

**Issue by King-Wizard** [calvincestari/CLCBannerNotifications#2]
2015-08-05 15:13:57.379 CLCBannerNotifications_Example[9624:280214] Unable to simultaneously satisfy constraints.
    Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 

```
(
    "<NSLayoutConstraint:0x7f949d033830 H:[UIImageView:0x7f949d01e6a0]-(0)-[UILabel:0x7f949d040150'Thanks for using CLCBanne...']>",
    "<NSLayoutConstraint:0x7f949d008800 UIImageView:0x7f949d01e6a0.right == UILabel:0x7f949d040150'Thanks for using CLCBanne...'.left - 15>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7f949d033830 H:[UIImageView:0x7f949d01e6a0]-(0)-[UILabel:0x7f949d040150'Thanks for using CLCBanne...']>
```

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.

**Comment by calvincestari** [comment]
This is fixed and available in 0.4.1 or later.
